@AssessmentApi_HostAddress = https://localhost:44383



GET {{AssessmentApi_HostAddress}}/api/Login?email=Azeezat@gmail.com&password=Azeezat@123

###

GET {{AssessmentApi_HostAddress}}/api/Login?email=string&password=string

###

POST {{AssessmentApi_HostAddress}}/api/AddEmployees
Content-Type: application/json

{
  //Employee
}

###

POST {{AssessmentApi_HostAddress}}/api/Login?email=Azeezat@gmail.com&password=Azeeza@123

###

GET {{AssessmentApi_HostAddress}}/api/GetEmployees

###
